disabled_rules:
  - line_length
  - force_cast
  - identifier_name
  - unused_closure_parameter
  - function_body_length
  - nesting
  - function_parameter_count
  - type_name
  - cyclomatic_complexity
  - type_body_length
  - file_length
  - large_tuple
included:
  - Gashaponmachines